COMPONENT=PlumSensingBaseAppC
CFLAGS += -I.. -I../universal_sensors
# CFLAGS += -DLOW_POWER_LISTENING
#CFLAGS += -I.. -I../tmote_onboard_sensors
CFLAGS += -DCC2420_DEF_CHANNEL=26

include $(MAKERULES)
