/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'PlumCmdMsg'
 * message type.
 */

public class PlumCmdMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 19;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = -1;

    /** Create a new PlumCmdMsg of size 19. */
    public PlumCmdMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new PlumCmdMsg of the given data_length. */
    public PlumCmdMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PlumCmdMsg with the given data_length
     * and base offset.
     */
    public PlumCmdMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PlumCmdMsg using the given byte array
     * as backing store.
     */
    public PlumCmdMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PlumCmdMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public PlumCmdMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PlumCmdMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public PlumCmdMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PlumCmdMsg embedded in the given message
     * at the given base offset.
     */
    public PlumCmdMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PlumCmdMsg embedded in the given message
     * at the given base offset and length.
     */
    public PlumCmdMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <PlumCmdMsg> \n";
      try {
        s += "  [cmdID=0x"+Long.toHexString(get_cmdID())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [senseRate=0x"+Long.toHexString(get_senseRate())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [rptRate=0x"+Long.toHexString(get_rptRate())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [battvol=0x"+Long.toHexString(get_battvol())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [blockStart=0x"+Long.toHexString(get_blockStart())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [blockEnd=0x"+Long.toHexString(get_blockEnd())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [unixTime=0x"+Long.toHexString(get_unixTime())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: cmdID
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'cmdID' is signed (false).
     */
    public static boolean isSigned_cmdID() {
        return false;
    }

    /**
     * Return whether the field 'cmdID' is an array (false).
     */
    public static boolean isArray_cmdID() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'cmdID'
     */
    public static int offset_cmdID() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'cmdID'
     */
    public static int offsetBits_cmdID() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'cmdID'
     */
    public short get_cmdID() {
        return (short)getUIntBEElement(offsetBits_cmdID(), 8);
    }

    /**
     * Set the value of the field 'cmdID'
     */
    public void set_cmdID(short value) {
        setUIntBEElement(offsetBits_cmdID(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'cmdID'
     */
    public static int size_cmdID() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'cmdID'
     */
    public static int sizeBits_cmdID() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: senseRate
    //   Field type: int, unsigned
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'senseRate' is signed (false).
     */
    public static boolean isSigned_senseRate() {
        return false;
    }

    /**
     * Return whether the field 'senseRate' is an array (false).
     */
    public static boolean isArray_senseRate() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'senseRate'
     */
    public static int offset_senseRate() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'senseRate'
     */
    public static int offsetBits_senseRate() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'senseRate'
     */
    public int get_senseRate() {
        return (int)getUIntBEElement(offsetBits_senseRate(), 16);
    }

    /**
     * Set the value of the field 'senseRate'
     */
    public void set_senseRate(int value) {
        setUIntBEElement(offsetBits_senseRate(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'senseRate'
     */
    public static int size_senseRate() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'senseRate'
     */
    public static int sizeBits_senseRate() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: rptRate
    //   Field type: int, unsigned
    //   Offset (bits): 24
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'rptRate' is signed (false).
     */
    public static boolean isSigned_rptRate() {
        return false;
    }

    /**
     * Return whether the field 'rptRate' is an array (false).
     */
    public static boolean isArray_rptRate() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'rptRate'
     */
    public static int offset_rptRate() {
        return (24 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'rptRate'
     */
    public static int offsetBits_rptRate() {
        return 24;
    }

    /**
     * Return the value (as a int) of the field 'rptRate'
     */
    public int get_rptRate() {
        return (int)getUIntBEElement(offsetBits_rptRate(), 16);
    }

    /**
     * Set the value of the field 'rptRate'
     */
    public void set_rptRate(int value) {
        setUIntBEElement(offsetBits_rptRate(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'rptRate'
     */
    public static int size_rptRate() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'rptRate'
     */
    public static int sizeBits_rptRate() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: battvol
    //   Field type: int, unsigned
    //   Offset (bits): 40
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'battvol' is signed (false).
     */
    public static boolean isSigned_battvol() {
        return false;
    }

    /**
     * Return whether the field 'battvol' is an array (false).
     */
    public static boolean isArray_battvol() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'battvol'
     */
    public static int offset_battvol() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'battvol'
     */
    public static int offsetBits_battvol() {
        return 40;
    }

    /**
     * Return the value (as a int) of the field 'battvol'
     */
    public int get_battvol() {
        return (int)getUIntBEElement(offsetBits_battvol(), 16);
    }

    /**
     * Set the value of the field 'battvol'
     */
    public void set_battvol(int value) {
        setUIntBEElement(offsetBits_battvol(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'battvol'
     */
    public static int size_battvol() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'battvol'
     */
    public static int sizeBits_battvol() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: blockStart
    //   Field type: long, unsigned
    //   Offset (bits): 56
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'blockStart' is signed (false).
     */
    public static boolean isSigned_blockStart() {
        return false;
    }

    /**
     * Return whether the field 'blockStart' is an array (false).
     */
    public static boolean isArray_blockStart() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'blockStart'
     */
    public static int offset_blockStart() {
        return (56 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'blockStart'
     */
    public static int offsetBits_blockStart() {
        return 56;
    }

    /**
     * Return the value (as a long) of the field 'blockStart'
     */
    public long get_blockStart() {
        return (long)getUIntBEElement(offsetBits_blockStart(), 32);
    }

    /**
     * Set the value of the field 'blockStart'
     */
    public void set_blockStart(long value) {
        setUIntBEElement(offsetBits_blockStart(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'blockStart'
     */
    public static int size_blockStart() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'blockStart'
     */
    public static int sizeBits_blockStart() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: blockEnd
    //   Field type: long, unsigned
    //   Offset (bits): 88
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'blockEnd' is signed (false).
     */
    public static boolean isSigned_blockEnd() {
        return false;
    }

    /**
     * Return whether the field 'blockEnd' is an array (false).
     */
    public static boolean isArray_blockEnd() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'blockEnd'
     */
    public static int offset_blockEnd() {
        return (88 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'blockEnd'
     */
    public static int offsetBits_blockEnd() {
        return 88;
    }

    /**
     * Return the value (as a long) of the field 'blockEnd'
     */
    public long get_blockEnd() {
        return (long)getUIntBEElement(offsetBits_blockEnd(), 32);
    }

    /**
     * Set the value of the field 'blockEnd'
     */
    public void set_blockEnd(long value) {
        setUIntBEElement(offsetBits_blockEnd(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'blockEnd'
     */
    public static int size_blockEnd() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'blockEnd'
     */
    public static int sizeBits_blockEnd() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: unixTime
    //   Field type: long, unsigned
    //   Offset (bits): 120
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'unixTime' is signed (false).
     */
    public static boolean isSigned_unixTime() {
        return false;
    }

    /**
     * Return whether the field 'unixTime' is an array (false).
     */
    public static boolean isArray_unixTime() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'unixTime'
     */
    public static int offset_unixTime() {
        return (120 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'unixTime'
     */
    public static int offsetBits_unixTime() {
        return 120;
    }

    /**
     * Return the value (as a long) of the field 'unixTime'
     */
    public long get_unixTime() {
        return (long)getUIntBEElement(offsetBits_unixTime(), 32);
    }

    /**
     * Set the value of the field 'unixTime'
     */
    public void set_unixTime(long value) {
        setUIntBEElement(offsetBits_unixTime(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'unixTime'
     */
    public static int size_unixTime() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'unixTime'
     */
    public static int sizeBits_unixTime() {
        return 32;
    }

}
