#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'LplControl'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 6

# The Active Message type associated with this message.
AM_TYPE = -1

class LplControl(tinyos.message.Message.Message):
    # Create a new LplControl of size 6.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=6):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <LplControl> \n"
        try:
            s += "  [period=0x%x]\n" % (self.get_period())
        except:
            pass
        try:
            s += "  [start_msec=0x%x]\n" % (self.get_start_msec())
        except:
            pass
        try:
            s += "  [length_sec=0x%x]\n" % (self.get_length_sec())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: period
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'period' is signed (False).
    #
    def isSigned_period(self):
        return False
    
    #
    # Return whether the field 'period' is an array (False).
    #
    def isArray_period(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'period'
    #
    def offset_period(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'period'
    #
    def offsetBits_period(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'period'
    #
    def get_period(self):
        return self.getUIntElement(self.offsetBits_period(), 16, 1)
    
    #
    # Set the value of the field 'period'
    #
    def set_period(self, value):
        self.setUIntElement(self.offsetBits_period(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'period'
    #
    def size_period(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'period'
    #
    def sizeBits_period(self):
        return 16
    
    #
    # Accessor methods for field: start_msec
    #   Field type: int
    #   Offset (bits): 16
    #   Size (bits): 16
    #

    #
    # Return whether the field 'start_msec' is signed (False).
    #
    def isSigned_start_msec(self):
        return False
    
    #
    # Return whether the field 'start_msec' is an array (False).
    #
    def isArray_start_msec(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'start_msec'
    #
    def offset_start_msec(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'start_msec'
    #
    def offsetBits_start_msec(self):
        return 16
    
    #
    # Return the value (as a int) of the field 'start_msec'
    #
    def get_start_msec(self):
        return self.getUIntElement(self.offsetBits_start_msec(), 16, 1)
    
    #
    # Set the value of the field 'start_msec'
    #
    def set_start_msec(self, value):
        self.setUIntElement(self.offsetBits_start_msec(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'start_msec'
    #
    def size_start_msec(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'start_msec'
    #
    def sizeBits_start_msec(self):
        return 16
    
    #
    # Accessor methods for field: length_sec
    #   Field type: int
    #   Offset (bits): 32
    #   Size (bits): 16
    #

    #
    # Return whether the field 'length_sec' is signed (False).
    #
    def isSigned_length_sec(self):
        return False
    
    #
    # Return whether the field 'length_sec' is an array (False).
    #
    def isArray_length_sec(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'length_sec'
    #
    def offset_length_sec(self):
        return (32 / 8)
    
    #
    # Return the offset (in bits) of the field 'length_sec'
    #
    def offsetBits_length_sec(self):
        return 32
    
    #
    # Return the value (as a int) of the field 'length_sec'
    #
    def get_length_sec(self):
        return self.getUIntElement(self.offsetBits_length_sec(), 16, 1)
    
    #
    # Set the value of the field 'length_sec'
    #
    def set_length_sec(self, value):
        self.setUIntElement(self.offsetBits_length_sec(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'length_sec'
    #
    def size_length_sec(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'length_sec'
    #
    def sizeBits_length_sec(self):
        return 16
    
