 #
 # This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 # This class includes values of some nesC constants from
 # ../Climate.h.
 #/

class ShellConstants:
    BSHELL_SENSE = 41
    BSHELL_TIME = 44
    BSHELL_BLINK = 40
    BSHELL_CONFIG = 43
    BSHELL_LERASE = 42

